apiVersion: v1
kind: ServiceAccount
metadata:
  name: envbin

---
apiVersion: v1
kind: Pod
metadata:
  name: envbin-sa
spec:
  serviceAccount: envbin
  containers:
    - name: envbin-sa
      image: mtinside/envbin:latest
      ports:
        - containerPort: 8080
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: node-reader
# rules:
# - apiGroups: [""] # "" indicates the core API group
#   resources: ["nodes"]
#   verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: envbin-read-pods
  namespace: default
subjects:
- kind: ServiceAccount
  name: envbin
  namespace: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
