Vagrant.configure("2") do |config|
  # Set the boot timeout to 10 minutes (600 seconds)
  config.vm.boot_timeout = 600
  
  config.vm.box = "aaronvonawesome/ubuntu-2404-cinnamon"# clean ubuntu with gui box
    # Enable drag and drop
    config.vm.provider "virtualbox" do |vb|
      vb.name = "UBUNTUWITHGUI"
      vb.gui = true
      vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.memory = "4096"
      vb.cpus = 3
    
    end


 

end
