services:
  db:
   image: mysql
   ports:
     - 3307:3306
   environment:
     - MYSQL_ROOT_PASSWORD=admin
   volumes:
     - sql-data:/var/lib/mysql
  phpmyadmin:
   image: phpmyadmin
   ports:
     - 5012:80
volumes:
 sql-data:  